### ISSUE TITLE
python3 helper.py -i init failed

### ISSUE THREAD

**Issue by qinyunchuan** [bukun/TorCMS#7]
I am using Python 3.5.2.  
But the following error occurs when init

```
 python3 helper.py -i init
Traceback (most recent call last):
  File "helper.py", line 3, in <module>
    from torcms.script.command import entry
  File "/home/ubuntu/TorCMS/torcms/script/command.py", line 10, in <module>
    from .script_init import run_init
  File "/home/ubuntu/TorCMS/torcms/script/script_init.py", line 8, in <module>
    from .script_gen_category import run_gen_category
  File "/home/ubuntu/TorCMS/torcms/script/script_gen_category.py", line 9, in <module>
    from openpyxl.reader.excel import load_workbook
  File "/home/ubuntu/.local/lib/python3.5/site-packages/openpyxl/__init__.py", line 6, in <module>
    from openpyxl.workbook import Workbook
  File "/home/ubuntu/.local/lib/python3.5/site-packages/openpyxl/workbook/__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "/home/ubuntu/.local/lib/python3.5/site-packages/openpyxl/workbook/workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "/home/ubuntu/.local/lib/python3.5/site-packages/openpyxl/worksheet/worksheet.py", line 392
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
```

**Comment by bukun** [comment]
I found your openpyxl using f-stirng.  Upgrade Python to 3.6 above. or install openpyxl compatible to Python 3.5 .

**Comment by qinyunchuan** [comment]
Thanks, I reinstalled the openpyxl 2.6.0 and it works!
```
pip3 uninstall openpyxl
pip3 install openpyxl==2.6.0
```
